server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DavidChavess/Spring-Cloud-Config-Supplier
        force-pull: true
        default-label: main